/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CommandDefinition = {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  /**
   * what the command should be called by
   */
  id: string;
  /**
   * whether this is a built in command
   */
  builtIn: boolean;
  /**
   * a short human readable description of the command
   */
  description: string;
  /**
   * optional url leading to external docs
   */
  helpUrl?: string;
  requiredPermission?:
    | "invite"
    | "ban"
    | "kick"
    | "acl"
    | "founder"
    | "upgrade"
    | "none"
    | "message"
    | "sticker"
    | "react"
    | "redactOthers"
    | "redactSelf"
    | "custom";
  checkSpacePermission?: boolean;
  /**
   * id of the custom permission needed for this command
   */
  customPermission?: string;
  /**
   * a required client config flag
   */
  requiredCofigFlag?: "developer";
  attributes?: {
    [k: string]: unknown;
  }[];
  /**
   * if this command can be called when you are currently replying to someone
   */
  executableInReply?: boolean;
  /**
   * additional information if this is a bot command
   */
  botCommand?: {
    /**
     * when this command overrides a built in command
     */
    override?: {
      /**
       * the id of the builtin command it overrides
       */
      overrides?: string;
      [k: string]: unknown;
    };
    /**
     * the mxid of the bot
     */
    botMxId: string;
    /**
     * the state event id which introduces/describes this command
     */
    stateEventId: string;
    [k: string]: unknown;
  };
  /**
   * in which category is this command
   */
  category: "core" | "developer" | "moderation" | "administration" | "cosmetics" | "misc" | "fun" | "persona" | "bot";
} & {
  /**
   * what the command should be called by
   */
  id: string;
  /**
   * whether this is a built in command
   */
  builtIn: boolean;
  /**
   * a short human readable description of the command
   */
  description: string;
  /**
   * optional url leading to external docs
   */
  helpUrl?: string;
  requiredPermission?:
    | "invite"
    | "ban"
    | "kick"
    | "acl"
    | "founder"
    | "upgrade"
    | "none"
    | "message"
    | "sticker"
    | "react"
    | "redactOthers"
    | "redactSelf"
    | "custom";
  checkSpacePermission?: boolean;
  /**
   * id of the custom permission needed for this command
   */
  customPermission?: string;
  /**
   * a required client config flag
   */
  requiredCofigFlag?: "developer";
  attributes?: {
    [k: string]: unknown;
  }[];
  /**
   * if this command can be called when you are currently replying to someone
   */
  executableInReply?: boolean;
  /**
   * additional information if this is a bot command
   */
  botCommand?: {
    /**
     * when this command overrides a built in command
     */
    override?: {
      /**
       * the id of the builtin command it overrides
       */
      overrides?: string;
      [k: string]: unknown;
    };
    /**
     * the mxid of the bot
     */
    botMxId: string;
    /**
     * the state event id which introduces/describes this command
     */
    stateEventId: string;
    [k: string]: unknown;
  };
  /**
   * in which category is this command
   */
  category: "core" | "developer" | "moderation" | "administration" | "cosmetics" | "misc" | "fun" | "persona" | "bot";
};

export interface CommandList {
  /**
   * a command
   *
   * @minItems 1
   */
  commands: [CommandDefinition, ...CommandDefinition[]];
}
